// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAXsHkoNtFyCPlILu62Vj50JJ3qfvaGNI',
    appId: '1:750311138513:web:411d6c79bfacb55d4b51f0',
    messagingSenderId: '750311138513',
    projectId: 'hotel-automation-software',
    authDomain: 'hotel-automation-software.firebaseapp.com',
    storageBucket: 'hotel-automation-software.firebasestorage.app',
    measurementId: 'G-QJMEB4NDM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkVxu5MG7KvwIs-2_rCZVuNezMxw9mXac',
    appId: '1:750311138513:android:b990a27235a269a74b51f0',
    messagingSenderId: '750311138513',
    projectId: 'hotel-automation-software',
    storageBucket: 'hotel-automation-software.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoV14J0AP9D4SvoFD3F3WVD4Cez--94pU',
    appId: '1:750311138513:ios:d4d1335ccfc8d91d4b51f0',
    messagingSenderId: '750311138513',
    projectId: 'hotel-automation-software',
    storageBucket: 'hotel-automation-software.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoV14J0AP9D4SvoFD3F3WVD4Cez--94pU',
    appId: '1:750311138513:ios:d4d1335ccfc8d91d4b51f0',
    messagingSenderId: '750311138513',
    projectId: 'hotel-automation-software',
    storageBucket: 'hotel-automation-software.firebasestorage.app',
    iosBundleId: 'com.example.seProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAXsHkoNtFyCPlILu62Vj50JJ3qfvaGNI',
    appId: '1:750311138513:web:81d33007523d7e444b51f0',
    messagingSenderId: '750311138513',
    projectId: 'hotel-automation-software',
    authDomain: 'hotel-automation-software.firebaseapp.com',
    storageBucket: 'hotel-automation-software.firebasestorage.app',
    measurementId: 'G-4TZ2VWGLYX',
  );
}
